openapi: 3.0.0
info:
  title: Search carsharing service
  version: '1.0'
  contact:
    email: nikolinapecnjak@gmail.com
    name: Nikolina Pecnjak
  description: This service allows us to search car sharing  services.
servers:
  - url: 'http://localhost:3000'
    description: Nikolina Pecnjak
paths:
  /carsharingService:
    get:
      tags:
        - autopartage
        - carsharing
      summary: Get cars available for carsharing according to the requester matching input parameters.
      description: 'It returns the list of CarsharingService objects administered by the requester and matching the input parameters. The response does not contain all the detailed information of the retrived cars, but just a subset of properties. All the query parameters are case insensitive.'
      operationId: getCarsharingServices
      parameters:
        - name: language
          in: query
          description: 'The language in which the content will be displayed, it is selected from the application. ISO 639-2 Code is used.'
          required: false
          schema:
            type: string
            example: hrv
          x-example: France
        - name: currency
          in: query
          description: 'The name of the currency in which the prices will be displayed, it is selected from the application. The official ISO 4217 standard which specifies three-letter ("Alpha-3") codes is used.'
          required: false
          schema:
            type: string
            example: EUR
          x-example: EUR
        - name: userCurrentLocation
          in: query
          description: If set to true the exact user location will be used to find the closest available cars.
          required: false
          schema:
            type: boolean
          x-example: France
        - name: country
          in: query
          description: The full name of the country where the carsharing service is being searched.
          required: false
          schema:
            type: string
            example: France
          x-example: France
        - name: city
          in: query
          description: The city where the carsharing service is being searched.
          required: false
          schema:
            type: string
            example: Nice
          x-example: Nice
        - name: zipcode
          in: query
          description: The zipcode of the city where the carsharing service is being searched.
          required: false
          schema:
            type: string
            example: '06100 '
          x-example: 6160
        - name: fullAddress
          in: query
          description: The full address for the wished location of car pickup.
          required: false
          schema:
            type: string
            example: 1er Albert Premier
          x-example: '27 Albert Premier,06160 Antibes'
        - name: stationName
          in: query
          description: 'The exact location name for the wished location of car pickup. It can be for example airport name, parking name or station name.'
          required: false
          schema:
            type: string
            example: Gare de Nice-Ville
          x-example: Nice Gare
        - name: startDate
          in: query
          description: 'The start date of the service following  RFC 3339 protocol conventions in the following format: YYYY-MM-DD. If omitted default value is current date at the time of the search. '
          required: true
          schema:
            type: string
            example: '2021-07-21'
            format: date
          x-example: '2017-07-21'
        - name: startDateTime
          in: query
          description: 'The start date and time of the service following  RFC 3339 protocol conventions in following format: YYYY-MM-DDTHH:MM:SSZ. If omitted default value is current date-time at the time of the search. '
          required: true
          schema:
            type: string
            format: date-time
          x-example: '2017-07-21T17:32:28Z'
        - name: carBrand
          in: query
          description: This parameter can be used for filtering results depending on the selected car brand.
          required: false
          schema:
            type: string
            example: BMW
          x-example: BMW
        - name: carClass
          in: query
          description: This parameter can be used for filtering results depending on the selected car class. Car classes should be listed in enum field.
          required: false
          schema:
            type: string
            example: A
          x-example: A
        - name: isAutomatic
          in: query
          description: If true only automatic cars will be returned.
          required: false
          schema:
            type: boolean
        - name: isElectric
          in: query
          description: If true only electric cars will be returned.
          required: false
          schema:
            type: boolean
        - name: isThermal
          in: query
          description: If true only the cars with thermal engine will be returned.
          required: false
          schema:
            type: boolean
        - name: isisHybride
          in: query
          description: If true only the hybride cars will be returned.
          required: false
          schema:
            type: boolean
        - name: isHybridRechargeable
          in: query
          description: If true only the hybrid rechargeable cars will be returned.
          required: false
          schema:
            type: boolean
        - name: numberOfSeats
          in: query
          description: If specified only the cars with selected number of seats will be returned.
          required: false
          schema:
            type: integer
            enum:
              - 1
              - 2
              - 3
              - 4
              - 5
              - 6
              - 7
            example: 4
          x-example: 4
        - name: snowTires
          in: query
          description: If true only the the cars with snow tires will be returned.
          required: false
          schema:
            type: boolean
        - schema:
            type: boolean
          in: query
          name: bookNow
          description: If true the startDateTime is set to the current local time which applies in the country that is selected for the search..
        - schema:
            type: string
            example: 123FGH453
          in: query
          name: contractCode
          description: Represents the code of autopartage reservation done through another service such as a Hotel provider.
        - schema:
            type: number
            format: double
            example: 43.575847
          in: query
          name: userXCoordinate
          description: Applicable only if userCurrentLocation parameter is true. Represents the X coordinate of current user location.
        - schema:
            type: number
            format: double
            example: 7.120708
          in: query
          name: userYCoordinate
          description: Applicable only if userCurrentLocation parameter is true. Represents the Y coordinate of current user location.
        - schema:
            type: string
            example: '2021-07-22'
            format: date
          in: query
          name: endDate
          description: 'The end date of the service following  RFC 3339 protocol conventions in the following format: YYYY-MM-DD.'
        - schema:
            type: string
            format: date-time
            example: '2021-07-22T17:32:28Z'
          in: query
          name: endDateTime
          description: 'The end date and time of the service following  RFC 3339 protocol conventions in following format: YYYY-MM-DDTHH:MM:SSZ.'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: array
                uniqueItems: false
                items:
                  $ref: ../models/CarsharingService.v1.yaml
              examples:
                example-1:
                  value:
                    - id: string
                      selectedCar:
                        id: string
                        pickupLocation:
                          id: string
                          country: string
                          city: string
                          zipCode: 0
                          fullAddress: string
                          stationName: string
                          description: string
                          isAirport: true
                          distanceFromSelectedLocation: string
                          options:
                            id: string
                            flightNumber: string
                            airline: Air France
                            departureCity: NCE
                            pickupTerminal: string
                            byPlaneArrival: true
                        carBrand: BMW
                        carModel: Fiat
                        fuelOrBatteryLevel: 70%
                        numberOfSeats: '4'
                        isAutomatic: true
                        isCabriolet: true
                        isElectric: true
                        isThermal: true
                        isHybrid: true
                        isHybridRechargeable: true
                        description: 'Equiped with climatisation and snow tires. '
                        fuelType: diesel
                        fuelCardIncluded: true
                        airConditioning: true
                        gps: true
                        snowTires: true
                        speedRegulator: true
                        halfAutonomyLevel: true
                        kilometersLeft: 1500
                        carClass: S
                        platesNumber: FW228GZ
                        carYear: 2017
                        kilometersPassed: 50000
                      startDate:
                        id: string
                        date: '2021-07-21'
                        dateTime: '2021-07-21T17:32:28Z'
                      returnDate:
                        id: string
                        date: '2017-07-21'
                        dateTime: '2017-07-21T17:32:28Z'
                      returnLocation:
                        id: string
                        country: string
                        city: string
                        zipCode: 0
                        fullAddress: string
                        stationName: string
                        description: string
                        isAirport: true
                        distanceFromSelectedLocation: string
                        options:
                          id: string
                          flightNumber: string
                          airline: Air France
                          departureCity: NCE
                          pickupTerminal: string
                          byPlaneArrival: true
                      additonalServices:
                        id: string
                        airportParkingService: true
                        airportParkingServicePrice: 100 EUR
                        airportParkingServiceDescription: string
                        includeSnowChains: true
                        snowChainsPrice: 100 EUR
                        snowChainsDescription: string
                        additionalDriversService: true
                        additionalDriversServicePrice: 100 EUR
                        additionalDriversServiceDescription: string
                        includeChildSeat: true
                        childSeatPrice: string
                        childSeatDescription: string
                        additionalMileage: 1000
                        additionalMileagePrice: 50 EUR
                        additionalMileageDescription: string
                      insurance:
                        id: string
                        insuranceType: plus
                        insuranceDescription: string
                        insuranceTotalPrice: 100 EUR
                      finalServicePrice: 100 EUR
                      contractCode: '12345'
                      totalUsageTime: 2 days
                      kilometersPassed: '550'
                      kilometerPrice: 1 EUR
                      hourPrice: 10 EUR
                      minutePrice: 0.5 EUR
                      dayPrice: string
                      package: daily
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/error'
        '401':
          description: Unauthorized. It basically stands for unauthenticated requests.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/error'
        '403':
          description: Forbidden. It basically stands for failing funcitional security checks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/error'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/error'
components:
  schemas:
    warning:
      required:
        - code
        - title
      properties:
        code:
          type: integer
          description: 'A machine-readable error code, that will enable the API Consumers to handle this type of error'
        title:
          type: string
          description: An error title. It can be localized.
        detail:
          type: string
          description: 'An easy-to-read explanation specific to this occurrence of the problem. It should give the API consumer an idea of what went wrong and how to recover from it. Like the title, this fields value can be localized.'
        documentation:
          type: string
          format: url
          description: A link to a web page or file with further documentation to help the API consumer resolve this error
        warningType:
          type: string
          description: The type could be an information message or a warning message. By default it is a warning unless sevirity is set to information.
    error:
      required:
        - status
        - code
        - title
      properties:
        status:
          type: integer
          description: 'The [HTTP status code](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml) of this response. This is present only in terminal errors which cause an unsuccessful response. In the case of multiple errors, they must all have the same status.'
        code:
          type: integer
          description: A machine-readable error code from the error table that will enable the API Consumers to handle this type of error
        title:
          type: string
          description: 'An error title from the error table with a 1:1 correspondence to the error code. This may be localized.'
        detail:
          type: string
          description: 'An easy-to-read explanation specific to this occurrence of the problem. It should give the API consumer an idea of what went wrong and how to recover from it. Like the title, this fields value can be localized.'
        documentation:
          type: string
          format: url
          description: A link to a web page or file with further documentation to help the API consumer resolve this error
